### ISSUE TITLE
Subtraction plot not showing

### ISSUE THREAD

**Issue by Sinah-astro** [twillis449/radio_source_analysis#1]
Hi Tony

I'm having an issue with the script that I execute to make the analysis
[test.txt](https://github.com/twillis449/radio_source_analysis/files/8123055/test.txt). It seems to not pop the window for subtracting sources just like in your tutorial. What could I be doing wrong? I attach the CSV file as well [PSZ2G254.08.csv](https://github.com/twillis449/radio_source_analysis/files/8123061/PSZ2G254.08.csv)

**Comment by twillis449** [comment]
Change line 17 of your script to
get_morphology_images.py PSZ2G254.08.csv 3 D 3 F F
i.e. that last T to an F. The T  is telling the program to run in batch mode, so without any human intervention.  Also it looks like your RA may not be specified correctly in the csv file as at the monent it would  just given as  46.07. I'm going to be changing the reading of the csv file so that the second field (given as xxxx in my example) is no longer used  - its a relic from an earlier project.

**Comment by Sinah-astro** [comment]
Oh, I see, thank you. I do not understand the last part of your statement. My target is at that RA, even in my display header.

**Comment by twillis449** [comment]
Glad that things are working.
