### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by 960801** [twillis449/radio_source_analysis#2]
Hi Tony

I am having a bit of a problem installing the code on my ubuntu 20.04.
I cloned the repo and since it's already executable  all that was left was to put it in a directory that points to PYTHONPATH:
Home/.local/lib/bin/python3.8/site-packages

however, when runinng "source example_script" it throws a "command not found" for each of the scripts.

**Comment by twillis449** [comment]
This is interesting. I think the PYTHONPATH environment variable is more for the use of importing modules.  So after setting up my PYTHONPATH to include /home/twillis/.local/bin (somewhat shorter than yours :) ) I can do:

twillis[twillis]> python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import get_galaxy_parameters
>>> import conv_imageeasy-install.pth
>>> import make_morphology_mask
But as you say when I then try to run an example_script indeed I get all those 'command not found' messages

BUT if I add  /home/twillis/.local/bin to my standard executable PATH then things work.  

I think that if one wants to add stuff into site-packages (or dist-packages) then you have to start modifying the easy-install.pth file and create an egg.  And I've never tried to do so.

**Comment by 960801** [comment]
I also manage to import the packages on python.
I have attempted multiple times to do the second bit with little to no success at all.
the main folder that the contains the scripts is in "/home" , meaning I have to add "/home/nhlanhla/.local/bin" to the main PATH, but nothing seems to be working at all.

Could you please walk me through the these steps "BUT if I add /home/twillis/.local/bin to my standard executable PATH"

**Comment by twillis449** [comment]
First of all, you need to replace 'twillis' by your user name, presumably 'nhlanhla'  in the line that is confusing you.

If your user account is 'nhlanhla' and you have put the executable scripts in subdirectory .local/bin below nhlanhia and have added /home/nhlanhia/.local/bin to your PATH environment variable,  then things 'should just work'  - famous last words :( 

This assumes that your user directory is under /home. If that's not the case that you would need to modify things. Also, you may need to log out and then log back in so that if. e.g. you are using a bash shell your login terminal is aware of the updates you have made to your .bashrc file to add the .loca/bin directory to your PATH environment variable.

I have the feeling that you may want to get some assistance from an IT support person at your institute
